name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your branch if different
  pull_request:
    branches:
      - main

jobs:
  deploy_backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Deploy to DigitalOcean Droplet
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          echo "$SSH_KEY" > key.pem
          chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${SSH_USERNAME}@${SSH_HOST} << 'EOF'
          cd /var/cardsServer
          git pull origin main
          npm install
          pm2 restart express-server
          EOF

